---
env:
  browser: true
  webextensions: true
  es6: true
rules:
  quotes: 0
  no-trailing-spaces: 0
  eol-last: 0
  no-unused-vars: 0
  no-underscore-dangle: 0
  no-alert: 0
  no-lone-blocks: 0
  indent:
    - error
    - tab
    - SwitchCase: 1
parserOptions:
  ecmaVersion: 8